version: "3.9"
services:
  web:
    image: baseimg/nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    networks:
      - principal
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8080:8080"
      - "9000:9000"
    depends_on:
        - mysql
  mysql:
    image: mysql:8.0.29
    volumes:
      - 'mysql_volume:/var/lib/mysql'
    environment:
      MYSQL_PASSWORD: a159753b654852c
      MYSQL_USER: ci4
      MYSQL_ROOT_PASSWORD: a159753b654852c
      MYSQL_DATABASE: ci4-crud-test
    networks:
      - principal
    ports:
      - 3306:3306
networks:
    principal:
        driver: bridge
volumes:
    mysql_volume:
        driver: local